// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MobileNavController from "./mobile_nav_controller"
application.register("mobile-nav", MobileNavController)

import WorkWeekController from "./work_week_controller"
application.register("work-week", WorkWeekController)
