secret_key_base: "output from `rails secret`"
registration_salt: "c4e6c76466dcc4727264807ceae275c93ce8e421a57f30396699a3e09af5258d90a6458cd90b3ca04eb542946f08de349430e83e63d05ea06c91bd5dfe80e34e"

stripe_api_key: "https://dashboard.stripe.com/test/apikeys - secret key"
stripe_price_id: "output from stripe bootstrap script"
stripe_signing_secret: "set up an endpoint at https://dashboard.stripe.com/test/webhooks, copy the signing secret"
stripe_customer_portal_url: 'output from stripe bootstrap script'
stripe_redirect_host: "http://localhost:3000"
rollbar_access_token: ""
