services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
      PREFAB_DATASOURCES: LOCAL_ONLY
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - sidekiq
    volumes:
      - .:/rails
      - ./public:/rails/public
    ports:
      - "3000:3000"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
      PREFAB_DATASOURCES: LOCAL_ONLY
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
      - ./public:/rails/public

volumes:
  bundle_path:
  redis:
  data:
