services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      PREFAB_DATASOURCES: LOCAL_ONLY
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/rails
      - ./public:/rails/public
    ports:
      - "3000:3000"

  solid_queue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rake solid_queue:start
    environment:
      DB_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      PREFAB_DATASOURCES: LOCAL_ONLY
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/rails
      - ./public:/rails/public

volumes:
  bundle_path:
  data:
