# Name of your application. Used to uniquely configure containers.
service: staffplan-redux

# Name of the container image.
image: fermion/staffplan-redux

# Deploy to these servers.
servers:
  web:
    hosts:
      - 34.192.107.71
    cmd: bundle exec puma -C config/puma.rb
    options:
      "add-host": host.docker.internal:host-gateway
  job:
    hosts:
      - 34.192.107.71
    cmd: bundle exec sidekiq -C config/sidekiq.yml
    options:
      "add-host": host.docker.internal:host-gateway

# Credentials for your image host.
registry:
  username: fermion
  password:
    - DOCKER_REGISTRY_TOKEN

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 34.192.107.71
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DOCKER_REGISTRY_TOKEN
    - REDIS_URL
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

ssh:
  user: ubuntu

# Configure builder setup.
builder:
  arch: amd64

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:15
    host: 34.192.107.71
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'staffplan_redux'
        POSTGRES_DB: 'staffplan_redux_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
   image: redis:latest
   roles:
     - web
     - job
   port: 6379
   volumes:
     - data:/var/lib/redis/data

proxy:
  app_port: 3000

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2
