name: Add all issues to Staffplan v3 project board
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GOINVO_BOT_APP_ID }}
          private_key: ${{ secrets.GOINVO_BOT_PEM_KEY }}

      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/goinvo/projects/2
          github-token: ${{ steps.create_token.outputs.token }}
          labeled: needs-triage
          label-operator: NOT
